jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: run client
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        run: ./client.exe
